- name: Create local token directory
  file:
    path: "/tmp/k3s_token_workers"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Read K3s Token
  command: cat /tmp/k3s_token
  register: k3s_token
  delegate_to: localhost

- name: Install K3s on Worker
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" K3S_URL="https://{{ hostvars[groups['k3s-master'][0]]['ansible_default_ipv4']['address'] }}:6443" K3S_TOKEN="{{ k3s_token.stdout }}" sh -
  become: true